### ISSUE TITLE
nice work!

### ISSUE THREAD

**Issue by aquynh** [daniel-araujo/proctal#1]
looks like a fantastic tool! we linked to your work from our websites now: http://www.capstone-engine.org/showcase.html & http://www.keystone-engine.org/showcase/

keep it up, cheers.

**Comment by daniel-araujo** [comment]
I owe you a great amount of gratitude. Both Capstone and Keystone provide very attractive features to the command line interface of Proctal. There's still a lot of code that needs to be polished and many features need to be revised before I consider it a stable tool for general use, though. Regardless, this is a nice incentive to keep working on that goal. Thank you!
