### ISSUE TITLE
Failed to allocate memory.

### ISSUE THREAD

**Issue by SNBSniper** [daniel-araujo/proctal#2]
Any fix for running the c file in the repo when this error shows up? : Failed to allocate memory.

**Comment by daniel-araujo** [comment]
That depends on what was going on. What were you trying to do?

**Comment by SNBSniper** [comment]
Just ran the c code you have posted with no args

**Comment by daniel-araujo** [comment]
Just by typing `proctal` in the command prompt? I can't reproduce the problem.

**Comment by daniel-araujo** [comment]
Oh, I see. That error message appears when the program fails to allocate memory in an other process. I omitted thorough error checking to keep the example short. I'm going to guess that either the process does not exist or the program is not privileged enough to manipulate other processes.

**Comment by daniel-araujo** [comment]
Made the README file clear about this with commit 19dbe3999aeb1cfe6212a951f1cde333d279586f
